dogmatiq/testkit

engine/engine.go
PR to add two methods (ExecuteCommand and RecordEvent) to the dogma test engine to implement the `dogma.CommandExecutor` and `dogma.EventRecorder` interfaces.
=> added ExecuteCommand and RecordEvent  to Engine

engine/configurer.go, engine/engine.go, engine/engine_test.go, go.mod, go.sum
This contains changes necessary for the in-memory engine to work with these versions, the major feature of which is the requirement that handlers declare their produced message types.
It does not include any change that ensures that handlers only produce messages that they had previously declared. Such a change can be made in a future PR (see #13).
=> Update to enginekit 0.2.0 and dogma 0.3.0.

engine/configurer.go, engine/controller/aggregate/controller.go, engine/controller/aggregate/scope.go, engine/controller/integration/controller.go, engine/controller/integration/scope.go, engine/controller/process/controller.go, engine/controller/process/scope.go, go.mod, go.sum
This means an update to `enginekit` v0.3.0
=> Use `message.TypeContainer` for sets of produced types in controllers.

interface_test.go, test.go, test_test.go
This PR adds file and line information assertion reports (fixes #38) and to the sections of the verbose logging that correspond to the calls the user makes in their test (such as `Prepare()`, `ExecuteCommand()`, `AdvanceTimeBy()`, etc).
=> Add file/line information to log message section headings.

engine/engine.go, engine/engine_test.go, engine/fact/dispatch.go, engine/fact/logger.go, engine/fact/logger_test.go, engine/fact/observer_test.go, test_test.go
The previous behavior was to record a `DispatchCycleSkipped` fact and rely on the user's tests to capture the lack of activity as a result of the unrecognized message. Using a panic gives much more direct feedback.
=> Panic when an unrecognized message is given to the engine.

engine/controller/aggregate/controller.go, engine/controller/process/controller.go
These errors are somewhat internal to the engine, and as such they serve no interoperability purpose. I'm removing them solely to eliminate an unnecessary coupling to a shared module (enginekit, in this case).
=> Remove usage of enginekit errors.

compare/comparator_test.go, compare/fuzzy_test.go, engine/controller/aggregate/controller_test.go, engine/engine_test.go, engine/fact/logger_test.go, render/renderer_test.go, render/string_test.go, test_test.go, testoption_test.go
This is in preparation for a switch from `enginekit/config` to `configkit` (#48).
=> Use `dogma/fixtures` instead of `enginekit/fixtures`, where possible.

engine/fact/internal/logging/ginkgo_test.go, engine/fact/internal/logging/icon.go, engine/fact/internal/logging/icon_test.go, engine/fact/internal/logging/write.go, engine/fact/internal/logging/write_test.go, engine/fact/logger.go
This PR removes the dependency on `enginekit/logging` by duplicating it as an internal package (again, this was done once before and then reverted).
This is in preparation for #52.
=> Sever dependency on `enginekit/logging` 

assert/message_test.go, assert/user.go, assert/user_test.go
This PR adds the `assert.Should()` method, which allows the user to provide a function to be used as an assertion in the test runner.
Fixes #46.
=> Add `assert.Should()`, for specifying user-defined assertions.

CHANGELOG.md, assert/report.go, assert/user.go, assert/user_test.go
This PR changes `assert.Should()` (which is used to make custom assertions during a testkit test), to provide the user with an `*assert.T` value, which shares much of its interface with Go's `*testing.T`.
Like in a standard Go test, this `T` value can be used to mark the test as failed, log error messages, etc. This replaces the `error` return value that was used to signal an assertion failure prior to this PR.
The goal here is to allow user assertions to use any third-party packages that allow integration via their own `testing.T`-like interface, including, but not limited to Ginkgo and Gomega.
=> Provide a testing.T-like value to custom user assertions.

engine/engine.go, go.mod, go.sum
Fixes #84 
This PR adds a mutex to engine to allow it's public methods to be called from multiple goroutines.
This is more or less a convenience to avoid the user having to do it themselves.
=> Allow basic engine concurrency.

CHANGELOG.md, assert/user.go, assert/user_test.go, dogma.go, interface.go, runner.go, test.go
This PR renames the `assert.T` type to `S` (as in `Should()`, the function it's used with), and the `testkit.T` type to `TestingT`. 
This is to avoid conflicts between testkit packages and `testing` itself when dot-importing, as is common in tests.
=> Rename `T` types to avoid collisions with `testing.T`

CHANGELOG.md, test.go, test_test.go
=> Allow `nil` assertions when advancing the engine clock.

engine/controller/aggregate/controller.go, engine/controller/aggregate/controller_test.go
Fixes #104
This PR changes the underlying in-memory engine to avoid storing a "snapshot" of aggregate state to help catch errors of the kind discussed in #30.
=> Rebuild aggregate state from events on every command.

CHANGELOG.md, test.go, test_test.go, time.go
Partially addresses #110 
This PR replaces the two separate methods on `Test` for advancing time with a single method that takes an "advancer" function which computes the new "now". This allows for extensibility by implementing domain-specific "advancers", such as `ToNextBusinessDay()`, etc.
=> Replace `Test.AdvanceTime[By|To]()` with single `AdvanceTime()` method.

CHANGELOG.md, assert/assertion.go, assert/assertion_test.go, assert/composite.go, assert/composite_test.go, assert/message.go, assert/messagetype.go, assert/user.go, test.go, test_test.go
Fixes #110 
This PR changes the `assert.Assertion` interface around to allow for an `assert.OptionalAssertion` interface which is satisfied by all existing assertions as well as the new `assert.Nothing` value.
This allows `AdvanceTime()` to accept an `Optional` instead of an `Assertion`, thus removing the need to allow `nil` assertions which are unclear when seen in tests. It also helped clean up some of the internals of `Test` where assertions were optional.
=> Allow for optional assertions on AdvanceTime()

engine/configurer.go, engine/controller/aggregate/controller.go, engine/controller/aggregate/controller_test.go, engine/controller/aggregate/scope.go, engine/controller/aggregate/scope_test.go, engine/controller/integration/controller.go, engine/controller/integration/controller_test.go, engine/controller/integration/scope.go, engine/controller/integration/scope_test.go, engine/controller/panic.go, engine/controller/panic_test.go, engine/controller/process/controller.go, engine/controller/process/controller_test.go, engine/controller/process/scope.go, engine/controller/process/scope_test.go, engine/controller/projection/controller.go, engine/controller/projection/controller_test.go, engine/controller/projection/scope.go, engine/controller/projection/scope_test.go, engine/controller/unexpectedmessage.go
Partially addresses #29
This PR recovers from `dogma.UnexpectedMessage` panic values and "re-panics" with a `testkit/engine/controller.UnexpectedMessage` value which adds context about the message that was being handled and the method that was called when the original panic occurred.
=> Provide more context to UnexpectedMessage panics.

CHANGELOG.md, assert/assertion.go, assert/common_test.go, assert/composite.go, assert/composite_test.go, assert/message.go, assert/messagetype.go, assert/user.go, assert/user_test.go, internal/testingmock/mock.go, runner.go, runneroption.go, test.go, test_test.go, testoption.go
Fixes #6
This PR removes "verbose" mode entirely, instead it always prints full engine logs and assertion reports.
This was a bit of an evolution from the original purpose of #6 which was to let users know that they could get more information by passing `-v` to `go test` in the case of a failure.
I then thought it'd be better if to just show the full logs (that is, the engine logs in addition to the assertion report) in the case of a failure anyway.
Finally, I realised that this is basically the behavior of `go test` by default. If you log via the `t` object it only prints those log messages if the test fails (unless you pass `-v`, then it prints full logs).
So, in the interested of simplicity I decided to remove any "verbose-mode" so that testkit always behaves the same and the regular …
=> Remove verbose mode.

engine/controller/aggregate/controller.go, engine/controller/aggregate/controller_test.go, engine/controller/aggregate/scope.go, engine/controller/aggregate/scope_test.go
This PR updates testkit to allow the behavior documented in [ADR-17](https://github.com/dogmatiq/dogma/blob/master/docs/adr/0017-recreate-aggregate-after-destruction.md), some of which was already allowed, but untested.
=> Allow AggregateCommandScope.Destroy() and RecordEvent() to be called in any order.

assert/message.go, assert/message_test.go, engine/controller/aggregate/scope.go, engine/controller/aggregate/scope_test.go, engine/controller/integration/scope.go, engine/controller/integration/scope_test.go, engine/controller/process/scope.go, engine/controller/process/scope_test.go, engine/engine.go, engine/engine_test.go, go.mod, go.sum
This PR updates testkit to validate messages using the `dogma.ValidateMessage()` function from Dogma v0.10.0
Testkit now panics if you attempt to use an invalid message when:
- Recording an event from an aggregate
- Recording an event from an integration
- Executing a command from a process
- Scheduling a timeout from a process
- Asserting that an invalid command was executed
- Asserting that an invalid event was recorded
- Dispatching an invalid message via the test engine, which in turn covers:
- Executing a command via an `engine.CommandExecutor` (as returned by `Test.CommandExecutor()`)
- Recording an event via an `engine.EventRecorder` (as returned by `Test.EventRecorder()`)
- Executing a command via `Test.Prepare()`
- Recording an event via `Test.Prepare()`
- Executing a command via …
=> Panic when using invalid messages.

CHANGELOG.md, engine/controller/projection/controller.go, engine/controller/projection/controller_test.go, engine/controller/projection/scope.go, engine/fact/logger.go, engine/fact/logger_test.go, engine/fact/projection.go, engine/run.go
This PR adds basic support for projection compaction (added in Dogma v0.10.0) to testkit's in-memory engine implementation. It does not address testing compaction.
It calls `Compact()` for each projection message handler one every hour of elapsed "engine time".
=> Compact projections every hour.

action.go, test.go
This PR adds the `Action` interface, which will be the common interface implemented by all actions that can be performed within the context of a `testkit.Test`, ultimately replacing the `ExecuteCommand()`, `RecordEvent()`, `AdvanceTime()` and `Call()` methods.
**Note: This PR targets the `api-overhaul` branch, not `master`.** The existing `Prepare()` method has already been renamed to `PrepareX()` on that branch to make way for this new implementation while retaining all of the old functionality/tests throughout the overhaul.
In preparation for moving test actions from methods on `Test` to objects that can be used either in `Prepare()` or a future `Assert()` method.
No
=> [api overhaul] Add the `Action` interface.

expectation.go, test.go
This PR adds the `Expectation` interface and the related `Test.Expect()` method.
At the moment these are both aliases for existing types that will be refactored through the overhaul. I chose the name `Expectation` instead of sticking with `Assertion` mostly because we use`onsi/gomega` widely, and it has an existing `Assertion` type that conflicts when we "dot import" both `testkit` and `gomega`.
**Note: This PR targets the `api-overhaul` branch, not `master`.** 
To allow the use of any `Action` with any assertion (`Expectation`).
I'm not 100% sure about the name `Expectation`, though I do think `Test.Expect()` is a better name than `Test.Assert()` for the method.
=> Api overhaul expect

action.go, advancetime.go, assert/assertion.go, assert/composite.go, assert/composite_test.go, assert/message.go, assert/messagetype.go, assert/user.go, expectation.go, test.go
This PR replaces the `assert.Operation` enumeration, which was used so that assertions (now called "expectations") could change their behavior based on what test operation was being performed. It has been replaced with the `ExpectOptionSet` struct which models these behavioral changes directly.
To decouple of expectations from the actions they run under.
No
=> Replace operation enumeration with expectation options.

action.go, advancetime.go, advancetime_test.go, expectation.go, test.go
This PR changes the `Action` interface so that it does not require any knowledge of the expectation being performed.
Instead of an expectation being passed to `Action.Apply()`, the `Action.ConfigureExpect()` method is called when there *is* an expectation being performed, allowing the action to setup the default expectation option.
This allows actions to be applied without any expectation, eventually eliminating the need for `assert.Nothing`.
No
=> Decouple actions from expectations.

action.go, advancetime.go, runner.go, test.go
This PR moves the parameters of `Action.Apply()` into a new struct called `ActionScope`.
- To prevent breaking changes to the `Action` interface as more features that actions can control are added or changed.
- To expose explicitly only the values that the actions are allowed to manipulate. This is now complete yet, for example `AdvanceTime()` directly manipulates the unexported `.now` field of `Test`.
No
=> Encapsulate parameters to `Action.Apply()` with an `ActionScope` struct.

dispatch.go, dispatchcommand_test.go, dispatchevent_test.go, internal/inflect/inflect.go, internal/inflect/inflect_test.go
This PR adds the `RecordEvent()` action.
It shares a common underlying `Action` implementation with `ExecuteCommand()`.
Part of porting `Test` methods to `Action` implementations.
No
=> Add `RecordEvent()` action.

call.go, call_test.go, dispatchcommand_test.go
This PR adds the `Call()` action.
Part of porting `Test` methods to `Action` implementations.
No
=> Add the `Call()` action.

assert/assertion.go, test.go
This PR removes `assert.Nothing`, a no-op assertion.
All actions can now be performed via `Prepare()` if an assertion (expectation) is not needed, so there is no longer a need for a no-op assertion.
No
=> Remove `assert.Nothing`.

action.go, advancetime.go, call.go, test.go
This PR removes the `Test` object from `ActionScope` and replaces it with values that are allowed to be manipulated by actions.
Removes the need to manipulate the unexported internals of `Test` in actions.
No
=> Avoid using `Test` internals in actions.

CHANGELOG.md, interface.go, test.go
This PR removes the `tHelper` interface.
Fixes #149 
This interface was present largely because `ginkgo.GinkgoTInterface` did not provide the `Helper()` method, which has since been added.
No
=> Remove the `tHelper` interface.

advancetime_test.go, assert/tracker.go, call_test.go, dispatchcommand_test.go, dispatchevent_test.go, engine/engine.go, engine/engine_test.go, engine/fact/dispatch.go, engine/fact/logger.go, engine/fact/logger_test.go, engine/fact/skip.go, engine/fact/tick.go, engine/operationoption.go, go.mod, go.sum, test.go
This PR adds the `engine.EnableHandler()` option which allows enabling/disabling individual handlers while dispatching a message or ticking the engine.
- Partially addresses #56
- Fixes #108
In complex applications it will be necessary to enable/disable individual handlers in order to isolate tests to specific parts of the application. I suspect most likely this will occur when testing integrations and projections.
This option takes precedence over the existing `Enable[Aggregates|Projections|Processes|Integrations]()` options. I'm not sure if `Enable` is quite the right word given that passing a value of `false` is a very explicit *disable*.
For example ...
```go
myEngine.Tick(
ctx,
engine.EnableHandler("some-aggregate", false),
engine.EnableAggregates("foo", true),
)
```
The result of …
=> Allow enabling/disabling handlers individually.

action.go, advancetime_test.go, call_test.go, dispatchcommand_test.go, dispatchevent_test.go, test.go, testoption.go, testoption_test.go
This PR updates some internal terminology to refer to the test time as the "virtual clock" more consistently.
None
Internal naming consistency.
No
=> Use more consistency terminology surrounding the "virtual clock".

CHANGELOG.md, advancetime_test.go, assert/common_test.go, call_test.go, dispatchcommand_test.go, dispatchevent_test.go, test.go, testoption.go, testoption_test.go
This PR renames `WithOperationOptions()` to `WithUnsafeOperationOptions()`.
This is a `TestOption` that allows low level control of the engine used within the `Test`.'
Prepares for #156 
We want to discourage the use of this function so that we can hide the internals of the engine behind the `Test` facade.
No
=> Rename `WithOperationOptions()` to `WithUnsafeOperationOptions()`.

CHANGELOG.md, test.go, test_test.go, testoption_test.go
This PR adds the `Test.EnableHandlers()` and `DisableHandlers()` methods which can be used to enable/disable specific handlers by name for the duration of a test.
Fixes #156 
Projections and integration handlers often have many dependencies. They are disabled by default when testing to allow tests that focus on business logic to avoid initialization of these dependencies. 
This change gives a mechanism to enable specific projections/integrations that need to be engaged during the test. 
After this change a user should no longer need to use the `engine` package when testing.
No
=> `Test.EnableHandlers()` and `DisableHandlers()`.

action.go, action_test.go, advancetime.go, advancetime_test.go, assert/assertion.go, assert/message.go, assert/messagetype.go, call.go, call_test.go, composite.go, composite_test.go, dispatch.go, dispatchcommand_test.go, dispatchevent_test.go, expectation_test.go, satisfy.go, satisfy_test.go, test.go
This PR formalizes the concept of the "banners" that are rendered in the test logs when an action is performed.
In preparation for #162 
Actions are expected to render a banner before they produce any other log output. By adding the `Action.Banner()` method and performing the logging in `Test` we make `Action` implementors aware of this requirement.
By adding `Expectation.Banner()` we can improve the banners logged via `Expect()` to include information about the expectation as well.
For example, if you run the following test:
```go
test.Expect(
ExecuteCommand(ChangeEmailAddress{}),
assert.EventRecorded(EmailAddressChanged{}),
)
```
The banner shown in the logs will be:
```
--- EXPECT EXECUTING ChangeEmailAddress COMMAND TO RECORD A SPECIFIC EmailAddressChanged EVENT ---
```
No
=> Improve logging "banners".

CHANGELOG.md, engine/controller/aggregate/controller.go, engine/controller/aggregate/scope.go, engine/controller/integration/controller.go, engine/controller/panic.go, engine/controller/panic_test.go, engine/controller/process/controller.go, engine/controller/projection/controller.go, engine/panicx/doc.go, engine/panicx/ginkgo_test.go, engine/panicx/location.go, engine/panicx/location_test.go, engine/panicx/unexpectedmessage.go, engine/panicx/unexpectedmessage_test.go
This PR adds a new `panicx` package (within `engine`) for dealing with panic values that occur within the application or due to a misbehaving application implementation.
The existing `controller.ConvertUnexpectedMessagePanic()` has been moved to `panicx.EnrichUnexpectedMessage()`.
It improves the nasty code that deals with finding panic locations on the stack and adds a few additional tests.
Prepares for #162 
We need to allow the in-memory engine to panic when an application misbehaves (such as recording an invalid message) so that the developer can catch these issues. However, when using the engine within a test we want to add information about these panic values to a test report rather than just letting them unwind the stack fully.
No
=> Add panicx package.

engine/panicx/linenumber_test.go, engine/panicx/location.go, engine/panicx/location_test.go, engine/panicx/unexpectedmessage_test.go
This PR adds `panicx.LocationOfFunc()`, `LocationOfMethod()` and `LocationOfCall()`.
Prepares for #162 
We need to find the location of various handler method implementations in order to make good suggestions in test reports.
No
=> Add functions for getting the location of functions and calls.

CHANGELOG.md, engine/controller/aggregate/controller.go, engine/controller/aggregate/controller_test.go, engine/controller/aggregate/scope.go, engine/controller/aggregate/scope_test.go, engine/controller/integration/scope.go, engine/controller/integration/scope_test.go, engine/controller/process/controller.go, engine/controller/process/controller_test.go, engine/controller/process/scope.go, engine/controller/process/scope_test.go, engine/panicx/location_test.go, engine/panicx/unexpectedbehavior.go, engine/panicx/unexpectedbehavior_test.go
This PR adds the `panicx.UnexpectedBehavior` type and changes the engine to panic with this value whenever the application behaves in an unexpected way.
Prepares for #162 
These panic values were previously just strings.
We need to allow the in-memory engine to panic when an application misbehaves (such as recording an invalid event) so that the developer can catch these issues. However, when using the engine within a test we want to add information about these panic values to a test report rather than just letting them unwind the stack fully.
No
=> Add `panicx.UnexpectedBehavior`

engine/engine.go, engine/engine_test.go
This PR ensures that the engine always returns a `context.Canceled` or `context.DeadlineExceeded` if the context passed to `Engine.Dispatch()` or `Engine.Tick()` is canceled/times-out, even if the handlers within the engine return an error.
Fixes #180 
These changes let us tell if the engine itself was asked to stop or timed out (usually because a test timed out), vs an individual handler timing out while handling a message, for example.
No
=> Disambiguate engine-level context errors from handler-level errors.

engine/controller/aggregate/controller.go, engine/controller/aggregate/scope.go, engine/controller/integration/scope.go, engine/controller/process/controller.go, engine/controller/process/scope.go, engine/panicx/unexpectedbehavior.go, engine/panicx/unexpectedmessage.go, engine/panicx/unexpectedmessage_test.go, internal/location/doc.go, internal/location/ginkgo_test.go, internal/location/linenumber_test.go, internal/location/location.go, internal/location/location_test.go
This PR moves the `Location` type and its associated "constructors" into its own internal `location` package.
- #125 
- #162
- #175 
So that the `Location` type can be used inside actions and expectations.
No
=> Move `panicx.Location` into its own package.

action.advancetime.go, action.advancetime_test.go, action.call.go, action.call_test.go, action.dispatch.command_test.go, action.dispatch.event_test.go, action.dispatch.go, expectation.message.command_test.go, expectation.message.event_test.go, expectation.message.go, expectation.messagetype.command_test.go, expectation.messagetype.event_test.go, expectation.messagetype.go, expectation.satisfy.go, expectation.satisfy_test.go
This PR changes action/expectation functions that take `dogma.Message` values to validate using `dogma.ValidateMessage()` instead of just checking for `nil`.
I changed the panic message a little to accomodate this information, so I also changed the panic messages for other functions to use a similar format.
#135 (previous PR)
Some of these changes were made previously but they were lost during the #127 refactor.
No
=> Validate messages in actions and expectations.

action.advancetime.go, action.call.go, action.dispatch.go, action.go, action_test.go, expectation.composite.go, expectation.go, expectation.message.go, expectation.messagecommon.go, expectation.messagetype.go, expectation.satisfy.go, expectation_test.go, test.go
This PR splits the `Expectation` interface into two separate interfaces. The existing `Expectation` interface represents the expectation, such as "record a specific <foo> event". The new `Predicate` interface is the object that actually tests that a given set of facts satisfy that expectation.
Fixes #199 
- It makes `Expectations` stateless
- It prevents misuse of the `Expectation` interface, because you can no longer call things out of order
No
=> Split expectations into two separate interfaces.

expectation.composite.go, expectation.composite_test.go, expectation.go, expectation.message.go, expectation.messagetype.go, expectation.satisfy.go, expectation_test.go, test.go
This PR changes `Expectation.Predicate()` to return an error.
Prepares for #196 
This allows the expectation to indicate a failure before the Dogma application is started.
No
=> Allow `Expectation.Predicate()` to return an error.

action.dispatch.go, expectation.composite.go, expectation.go, expectation.message.command_test.go, expectation.message.commandcall_test.go, expectation.message.event_test.go, expectation.message.eventcall_test.go, expectation.message.go, expectation.messagecommon.go, expectation.messagetype.command_test.go, expectation.messagetype.commandcall_test.go, expectation.messagetype.event_test.go, expectation.messagetype.eventcall_test.go, expectation.messagetype.go, expectation.satisfy.go, expectation_test.go, internal/inflect/inflect.go, test.go
This PR "fails fast" if `ToExecuteCommand[OfType]()` or `ToRecordEvent[OfType]()` are passed a message of the wrong role.
Fixes #196 
We can check this without actually running the engine/application code, which makes the expectation reporting logic simpler.
No
=> Check roles of messages used in expectations.

engine/engineoption.go, engine/operationoption.go, test.go, testoption.go
This PR changes the various "functional option" types to use an interface with unexported methods.
None
To mitigate future BC breaks. This approach entirely hides the implementation details of the options from the user while still allowing references to the option type itself.
No
=> Use opaque types for functional options.

expectation.composite.go, expectation.go, expectation.message.go, expectation.messagecommon.go, expectation.messagetype.go, expectation.satisfy.go, expectation_test.go, test.go
This PR removes the `PredicateOptions` parameter from the `Expectation.Predicate()` method and instead places it inside the `PredicateScope`.
None
The purpose of the `PredicateScope` type is essentially to emulate key/value parameters to help minimize BC breaks to to the `Predicate` interface. It's counter to this goal to have a separate parameter for this options.
No
=> Put `PredicateOptions` inside `PredicateScope`.

expectation.message.go, expectation.messagecommon.go, expectation.messagetype.go
This PR changes the `tracker.Notify()` method to return the envelope of the "tracked" message within the fact.
None
Eliminates a bit of code that is duplicated across `messageExpectation` and `messageTypeExpectation`.
No
=> Return tracked envelope from `tracker.Notify()`.

action.advancetime.go, action.advancetime_test.go, action.call.go, action.call_test.go, action.dispatch.command_test.go, action.dispatch.event_test.go, action.dispatch.go, action.go, action_test.go, expectation.composite.go, expectation.composite_test.go, expectation.go, expectation.message.go, expectation.messagetype.go, expectation.satisfy.go, expectation.satisfy_test.go, expectation_test.go, internal/report/message_test.go, test.go
This PR replaces the `Banner()` method on `Action` and `Expectation` with a `Caption()` method.
Prepares for #162
In preparation for the new reporting system (which will support multiple report renderers) we don't want to be making stylistic choices (such as `Banner()`'s uppercase formatting) within the actions and expectations; this should be the responsibility of the renderer.
~The `report.LazyString` type allow deferring interpolation of format placeholders until the rendering stage. This would allow, for example, substituted parts of strings to be placed in bold in a hypothetical HTML renderer.~
For the time being (that is, before #162 is done) the existing logs show the captions exactly as they are presented (in lower case).
No
=> Replace "banners" with lazily evaluated "captions".

CHANGELOG.md, expectation.messagematch.event_test.go, expectation.messagematch.go
This PR adds `ToRecordEventMatching()`, the event-specific companion to `ToExecuteCommandMatching()` that was added in #226.
To provide the same flexibility when matching events as is available for commands.
No
Fixes #126
=> Add `ToRecordEventMatching()` expectation.

expectation.messagematch.command_test.go, expectation.messagematch.event_test.go, expectation.messagematch.go
- Use consistent language in the expectation functions names and the error messages when the expectation fails (satisfies vs matches)
- Include the location (file/line) of the predicate function in the error message
Just to avoid confusion that might occur by using different terms. Both of these changes to tie the error message to the specific expectation you are making a little better.
No
None
=> Unify language used in expectations and their reports.

CHANGELOG.md, expectation.messagematch.commandonly_test.go, expectation.messagematch.eventonly_test.go, expectation.messagematch.go
This PR adds the `ToOnlyExecuteCommandsMatching()` and `ToOnlyRecordEventsMatching()` expectations.
These expectations allow the user to set universal requirements on all executed commands (or recorded events) for the duration of a call to `Test.Expect()`.
We have a use-case for this in proprietary products that I can't describe here, but essentially we want to ensure that a specific command type is never executed with a specific value in one of its fields while the application is in a certain state, even though that value is allowed at other times.
We can expand on this functionality in the future by allowing the user to provided test-wide expectations, so we can enforce this behavior for the lifetime of a `Test` object, not only in a single call to `Test.Expect()`.
No
None
=> Add `ToOnly[ExecuteCommands|RecordEvents]Matching()`.

CHANGELOG.md, action.call.go, action.go, executor.go, executor_test.go, test.go
This PR adds the `InterceptCommandExecutor()` option which allows the user to install a hook function that is called whenever a command is executed via `Test.CommandExecutor().ExecuteCommand()`.
So that we can simulate errors within a `CommandExecutor` for testing error-handling paths.
No
Partially addresses https://github.com/dogmatiq/testkit/issues/233
- I am yet to add a similar option for `EventRecorder`
- I also want to add a `CallOption` as mentioned in the issue, and make this option usable there as well
=> Add `InterceptCommandExecutor()` option.

CHANGELOG.md, action.call.go, executor.go, executor_test.go, testoption.go
This PR adds functional options to the `Call()` action.
To allow use of the `InterceptCommandExecutor()` option for both an entire `Test` and an individual `Call()`.
No
Partially addresses https://github.com/dogmatiq/testkit/issues/233
Note that this is being merged back into the `interceptor` branch.  Once this is done I will basically repeat what I've done for command executors so that we have the same features for event recorders.
=> Add `CallOption` function optional to `Call()`.

CHANGELOG.md, engine/engine.go, engine/executor.go, engine/executor_test.go, engine/recorder.go, engine/recorder_test.go
This PR changes `engine.CommandExecutor` and `EventRecorder` to use more meaningful panic messages when the user passes an unrecognised message or a message of the wrong role.
Prior to this change the panic message would indicate the role was wrong, without mentioning the type of the message or what role was expected. Worse, if the message was not known to the engine the expected role itself is invalid so you'd get a panic from the internals of the `configkit/message.Role` type.
No
Fixes #254
=> Improve panic messaging from `engine.CommandExecutor` and `EventRecorder`.

expectation.composite.go, expectation.composite_test.go, expectation.go, expectation.message.command_test.go, expectation.message.event_test.go, expectation.message.go, expectation.messagematch.command_test.go, expectation.messagematch.event_test.go, expectation.messagematch.go, expectation.messagetype.command_test.go, expectation.messagetype.event_test.go, expectation.messagetype.go, expectation.repeat.go, expectation.satisfy.go, expectation.satisfy_test.go, expectation_test.go, report.go, test.go
This PR is a refactoring of #346, and targets its branch, not `main`.
=> Refactor 6157adf to allow expectations to control what's reported when inverted.
